version: "3"

services:
  eureka-server-master:
    image: loc-cloud-component/eureka-server
    hostname: eureka-server-master             # 指定hostname
    restart: always
    container_name: eureka-server-master
    ports:
      - "1314:1314"
    environment:
      - spring.profiles.active=master
  eureka-server-slave:
    image: loc-cloud-component/eureka-server
    hostname: eureka-server-slave
    restart: always
    container_name: eureka-server-slave
    ports:
      - "1315:1314"
    environment:
      - spring.profiles.active=slave